### ISSUE TITLE
Create a way for the Gemini API to call functions

### ISSUE THREAD

**Issue by ogallagher** [hoanghm/GeminiDev2024#9]
# (Co-)Dependencies

- Webpage prompts Gemini #14

**Comment by hoanghm** [comment]
Google makes it very easy to use Function Calling with the Gemini API. We won't need to create any class to handle function calling logic like we would with OpenAI API. 

There are mainly 2 ways:
I. (Easier) Using the built-in `ChatSession`  which will handle function calling automatically until a final response is obtained (requires the implementation of a function)
2. (More Flexible): Describe the function, the API will send a response containing the parameter values and the functions it want us to call and send back their values (doesn't require an implementation of a function)

Details included in the Notion page: https://www.notion.so/Gemini-API-Notes-5c4626fac4764315b4e6bbdd0ed025d5?pvs=4#8bdb2de7bfe94f50ac4472d5f9fdee72
